# -*- coding: utf-8 -*-
"""Numpy&Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9W1RGXEQuxyVbWktzIvlbF4v15GpLwC
"""

import numpy as np
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)



















import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
a=np.zeros((3,3),dtype=int)
print(a)
b=np.ones((2,2),dtype=int)
print(b)
a_range=np.arange(10)
print(a_range)
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)

arr1=np.array([1,2,3,4,5])
print(arr1)
arr2=np.array([3,4,5,6,7])
print(arr2)
result=arr1+arr2
print(result)
arr1=np.array([1,2,3,4,5])
print(arr1)
b=arr1+3
print(b)

a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([3,4,5,6,7])
print(a2)
a3=np.vstack(a1+a2)
print(a3)
a1=np.array([1,2,3,4,5])
print(a1)
a2=np.array([3,4,5,6,7])
print(a2)
a3=np.stack(a1+a2)
print(a3)
c=np.array([1,2,3,4,5,6,7,8])
b=np.split(c,4)
print(b)

a1=np.array([[1,2,3,4],[5,6,7,8]])
print(a1)
b=a1.T
print(b)

b1=np.array([[1,2],[3,4]])
print(b1)
b2=np.array([[5,6],[7,8]])
print(b2)
c1=np.dot(b1,b2)
print(c1)
d1=np.linalg.eig(c1)
print(d1)
e1=np.array([[1,2,3],[4,5,6]])
print(e1)
e2=np.array([[1,2,3],[4,5,6]])
print(e2)
e3=np.sum(e1+e2)
print(e3)

e1=np.array([[1,2,3],[4,5,6]])
print(e1)
e4=np.sum(e1,axis=0)
print(e4)
e5=np.sum(e1,axis=1)
print(e5)
arr11=np.array([1,2,3,4,5])
print(arr11)
arr22=np.mean(arr11)
print(arr22)
arr33=np.median(arr11)
print(arr33)
arr44=np.var(arr11)
print(arr44)
arr55=np.std(arr11)
print(arr55)
data=np.loadtxt("/content/txt_a.txt")
print(data)
data=np.loadtxt("/content/txt_a.txt",dtype=int)
print(data)
data=np.savetxt("/content/txt_b.txt",data)
print(data)

import matplotlib.pyplot as plt
a=np.array([1,2,3,4,5,6,7,8,9,10])
plt.plot(a)



import pandas as pd
a=["Jwalitha","Ramya","Durga","Jahnavi","Lahari","sunny","Dhanush"]
r=pd.Series(a,index=[67,43,44,89,34,45,73])
print(r)
df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)
df=pd.read_csv("/content/netflix_revenue_updated.csv",sep=" ")
print(df)
df=pd.read_csv("/content/file1.txt",sep=" ")
print(df)



df=pd.read_excel("/content/salesworkload.xlsx",sheet_name=1)
print(df)

df=pd.read_csv("/content/netflix_revenue_updated.csv",sep=" ")
print(df.loc[1])
df=pd.read_csv("/content/file1.txt",sep=" ")
print(df.loc[1])

import pandas as pd
df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)
a=df.head(5)
b=df.tail(5)
total_data=pd.concat([a,b],axis=0)
total_data.to_csv("c")
print(total_data.groupby(['EMEA Streaming Revenue'])['LATM Streaming Revenue'].count())

df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)
df=df.drop_duplicates()
print(df)



df=pd.read_csv("/content/netflix_revenue_updated.csv")
print(df)







from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color="black")
plt.title("IndvsAus_score")
plt.show

import numpy as np
import matplotlib.pyplot as plt
#Generate array of 200 values between pi &pi
tiger=np.linspace(-2*np.pi,2*np.pi,50)
print(tiger)

plt.plot(tiger,np.sin(tiger),color="black")
#plt.plot(x,y,,color,lables....)
plt.title("sin(x)")

import numpy as np
import matplotlib.pyplot as plt
#creating X
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
#creating y
runs_i=np.array([25,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
#plotting
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color="blue",label="India")
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color="black",label="Aus")
plt.legend(loc="best")
#plt.subplot(2,1,2)
#plt.subplot(2,1,1)

import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years=[1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color="hotpink",linewidth="3",label="CompanyA",marker=".",ms="15",mec="k")
plt.legend(loc="best")
plt.subplot(2,1,1)
plt.plot(years,profit_b,color="black",linestyle="dotted",label="CompanyB",marker="*")
plt.legend(loc="best")
#plt.subplot(2,1,2)

import matplotlib.pyplot as plt
a=np.array([25,60,5,10])
labe=["AIML","python","pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=180,textprops={'fontsize':32})
plt.show()
plt.figure(figsize=(100, 50))

import matplotlib.pyplot as plt
a=np.array([25,60,5,10])
labe=["AIML","python","pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels=labe,explode=explo,startangle=180,textprops={'fontsize':32})
plt.show()

import matplotlib.pyplot as plt
a=np.array([25,60,5,10])
labe=["AIML","python","pandas","Numpy"]
plt.pie(a,labels=labe)
co=["green","yellow","black","purple"]
plt.pie(a,colors=co)

plt.show()

import pandas as pd
import numpy as np
# Load the dataset containing daily temperatures
# Assuming the dataset is in a CSV file named 'temperature_data.csv' with a column named 'temperature'
df = pd.read_csv('/content/city__temperature.csv')
print(df)


average_temperature = df['AvgTemperature'].mean()
highest_temperature = df['AvgTemperature'].max()
lowest_temperature = df['AvgTemperature'].min()
threshold = 30
days_above_threshold = df[df['AvgTemperature'] > threshold].shape[0]


print("Average temperature for the month:", average_temperature)
print("Highest temperature recorded:", highest_temperature)
print("Lowest temperature recorded:", lowest_temperature)
print("Number of days where temperature exceeded", threshold, "degrees Celsius:", days_above_threshold)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("/content/plot.csv")
print(df)
print("Least Temperature Noted in January:\n",df.min())
print("Heightest Temperature Noted in January:\n",df.max())
c=df['JAN'].mean()
print("Average Temperature in the Month of January",c)
year = np.arange(1901,1950)
temp=np.array([22.4,24.93,23.44,22.5,22,22.28,24.46,23.57,22.67,23.24,23.22,23.7,23.71,24.42,22.6,24.13,23.68,22.06,23.32,22.87,23.57,22.96,23.25,22.84,22.56,23.54,23.23,23.33,23.05,22.6,24.57,24.13,22.85,22.76,22.28,23.1,23.34,22.95,23.61,23.79,23.18,22.99,22.97,23.17,22.38,24.41,22.61,22.87,24.31])
plt.plot(year,temp,color='black',label="x-axis=year\ny-axis=temp")
plt.legend(loc='best')
plt.title("Temperatures in January")
plt.show()